name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'  # Utilisez la même version que dans votre Dockerfile

      - name: Install dependencies
        run: npm install

      - name: Build Angular app
        run: npm run build

      - name: Build Docker image
        run: |
          docker build -t registry.mathieu-symphorien.fr/caille-fort-caille-fort:latest .
        env:
          DOCKER_BUILDKIT: 1

      - name: Log in to Docker registry
        run: echo "t" | docker login registry.mathieu-symphorien.fr --username "t" --password-stdin

      - name: Push Docker image
        run: |
          docker push registry.mathieu-symphorien.fr/caille-fort-caille-fort:latest